src/App.tsx
src/components/popups/PopupMenu.tsx
src/services/commands.ts
src/services/github.ts

This can be tested by changing `defaultGithubContext.branch` to `"rename-in-one-commit"` (a test branch on `isaac-content-2`, should be deleted once this is sorted).

Rename in one commit

---

src/components/semantic/Inserter.tsx
src/components/semantic/presenters/CardPresenter.tsx
src/components/semantic/presenters/FigurePresenter.tsx
src/services/commands.ts
src/services/config.ts
src/services/github.ts

Adds editable fields for title and subtitle to the card content block. Also removes the IsaacCard and IsaacCardDeck options from the "create page" modal and adds IsaacCardDeck to the "new content block" modal.
Also adds the ability to preview assets packaged with the frontend, which are still used in some places.

Add editor support for IsaacCardDeck

---

src/components/semantic/ExpandableText.tsx
src/components/semantic/presenters/ItemQuestionPresenter.tsx
src/components/semantic/styles/question.module.css

A good example is section 7 and 8 of Matthew Rihans test page: https://editor.isaacphysics.org/edit/master/content/beta_pages/matthew/matthew_practice.json
Previously:
With this change:

Overflowing entries in item choice dropdown menu

---

src/components/semantic/presenters/CodeSnippetPresenter.tsx
src/components/semantic/props/EditableText.tsx

Any `EditableDocPropFor` component with `format="code"` now uses CodeMirror for editing rather than a standard textbox

Use CodeMirror for text props formatted as "code"

---

src/components/semantic/presenters/FigurePresenter.tsx
src/isaac/IsaacTypes.ts
src/isaac/WithFigureNumbering.tsx

IMO we shouldn't try to generate figure numbers for figures in question feedback (or anything that doesn't exist in the document on page load). 
It's too complicated to get it right and I think any halfway-decent solution will be hard to implement/hard for the content teams to use and adapt to. It's also an edge case that doesn't occur often, so it is not worth looking much into.
This PR marks figures in question feedback as 'non-static' in the editor, and a warning message is shown indicating that the figure won't be given a number and so won't be referenceable with `\ref{...}`. This at least makes it transparent to the content team what's going on and why.
Section 4 of [this page](https://editor.isaacphysics.org/edit/master/content/questions/maths/functions/general_functions/alevel/funct …

Stop trying to generate figure numbers for non-static figures

---

src/components/semantic/presenters/FigurePresenter.tsx

The logic to handle SVG images effectively assumes they all make use of views, which is not the case for most SVGs in the content repo. This PR changes the logic so that any SVG with a view is handled differently, whereas standard SVG references are inlined as before.

Inline/refer to SVGs based on absence/presence of views, disregarding source

---

src/components/semantic/presenters/ChoicePresenter.tsx
src/components/semantic/presenters/ItemQuestionPresenter.tsx
src/isaac/IsaacTypes.ts
src/utils/content.ts

Counts drop zones in the question exposition and prefills choices with `{dropZoneCount}` number of "Any item" (wildcard?) items. When items are deleted they are replaced by a wildcard (or rather they are deleted, and a wildcard is appended to the end of the choice).
Effectively stops the user from creating cloze question choices with the wrong number of items, and makes sure they are in the format that the cloze question (back|front)end code can handle.

Add proper support for the null cloze item placeholder for empty zones

---

src/components/semantic/Metadata.tsx
src/components/semantic/metaItems.tsx
src/services/github.ts

Involves threading the app context object into `hasWarning` meta item callbacks.

Only warn of changing ID of published page, if page is actually published

---

src/components/MarkupToolbar.tsx
src/components/TopMenu.tsx
src/components/popups/PopupDropZoneInsert.tsx
src/components/popups/PopupGlossaryTermSelect.tsx
src/components/semantic/JSONEditor.tsx
src/components/semantic/presenters/BaseValuePresenter.tsx
src/components/semantic/props/EditableText.tsx

Also improves the toolbar when the editor gets a bit small, by summarising/collapsing/simplifying the toolbar options a bit when the CodeMirror editor is under 500px wide.

Add "Save" and "Cancel" options to toolbars in all CodeMirror editors

---

package.json
src/components/SemanticEditor.tsx
src/components/TopMenu.tsx
src/components/semantic/SemanticItem.tsx
src/components/semantic/SemanticRoot.tsx
src/components/semantic/presenters/BaseValuePresenter.tsx
src/components/semantic/presenters/ChoicePresenter.tsx
src/components/semantic/presenters/ContentValueOrChildrenPresenter.tsx
src/components/semantic/presenters/ItemQuestionPresenter.tsx
src/components/semantic/presenters/ListChildrenPresenter.tsx
src/components/semantic/presenters/TabsPresenter.tsx
src/components/semantic/presenters/pagePresenters.tsx
src/components/semantic/props/SemanticDocProp.tsx
src/components/semantic/props/listProps.tsx
src/components/semantic/registry.tsx
src/screens/EditorScreen.tsx
src/styles/editor.module.css
src/utils/inversePatch.ts
src/utils/keyedListHook.ts
yarn.lock

If we want to have a general "undo anything" button, there's a weird edge case with `PromotableValuePresenter` (I think) - when "Undo" is pressed, the presenter doesn't update its displayed value, but does if you force it to re-render another way. 
Because of this annoying edge case, I've made it so that actions are only recorded as "undoable" at the level of whatever calls `update`, i.e. the accordion section deletion function passes a flag to `update` saying "allow this action to be undone".
As a rule of thumb structural changes (deleting or moving tabs, accordion sections, content blocks etc.) can be undone without any problems (as far as I can tell).
Currently only deletions are marked as invertible, and only one "last action" is recorded at a time.
I've added a flash to the undo …

Undo button

---

src/components/CDNUploadModal.tsx
src/components/FileBrowser.tsx
src/components/GitHubDirInput.tsx
src/components/popups/Popup.tsx
src/components/popups/PopupMenu.tsx
src/utils/strings.ts

This makes the CDN upload modal wayyy easier to use and allows content to delete and rename files easily. 
There is still the issue that deletion, renaming and addition of files doesn't update the file tree, but we have some of those problems in the main content file tree already.
I refactored the `Files` and `PopupMenu` components to be a bit more generic; the main thing to check is that this refactor hasn't broken the main content file tree (`FileBrowser`) and it's related right-click popup menu(s).

Add file tree to the CDN modal allowing file deletion and renaming

---

src/components/popups/PopupGlossaryTermSelect.tsx

Only glossary inlines can be titled. Ada automatically selects the titled option

Add checkbox option for titled inline glossary terms to content editor

---

src/components/semantic/ChoiceInserter.tsx
src/components/semantic/Inserter.tsx
src/components/semantic/presenters/ChoicePresenter.tsx
src/components/semantic/presenters/ChoicesPresenter.tsx
src/components/semantic/presenters/InlinePartsPresenter.tsx
src/components/semantic/presenters/InlineQuestionTypePresenter.tsx
src/components/semantic/presenters/ListChildrenPresenter.tsx
src/components/semantic/presenters/questionPresenters.tsx
src/components/semantic/props/EnumProp.tsx
src/components/semantic/registry.tsx
src/isaac-data-types.d.ts

Inline questions are generated by first creating an InlineRegion, a new content type (_not_ a question type, as an inline region is by itself not a question but a wrapper for multiple individual questions). The inline region has a content field at the top in which to write the question as normal. To add an inline question, write `[inline-question:{some_id}]` anywhere in the content field; this can be in plaintext, inside tables, etc. It can work inside KaTeX-rendered expressions, however this is not explicitly supported and breaks the KaTeX screenreader text generation so is not advised.
Next, click "Add new inline question part" underneath the content. By setting the ID of this new question part to `inline-question:{some_id}`, this links the content to the question part. Underneath this, …

Add Inline Questions to editor

---

src/components/semantic/presenters/questionPresenters.tsx

When the defalult feedback box is removed, it was previously being set to a content object with an empty children array, thus showing in the editor as a "Please choose a block type" block, rather than the original empty content block.

Nullify default feedback value when deleting

---

src/components/semantic/presenters/InlineQuestionTypePresenter.tsx

This removes the call to `changeQuestionType` that was resetting values in the checkboxes for inline numeric questions. The type of the question was being changed _prior to calling `changeQuestionType`_, meaning the `requireUnits`, `disregardSignificantFigures` and `displayUnit` fields may have been populated already. In the particular case of `requireUnits` _not_ being present but the others being there, running `changeQuestionType` would reset the other fields. This was leading to particularly inconsistent behaviour as this would not happen if `requireUnits` was _present_ irrespective of its value, (c.f. `changeQuestionType`'s definition).

Prevent inline numeric question checkbox resetting

---

src/components/semantic/ChoiceInserter.tsx
src/components/semantic/Inserter.tsx
src/components/semantic/presenters/ChoicePresenter.tsx
src/components/semantic/presenters/questionPresenters.tsx
src/components/semantic/registry.tsx
src/isaac-data-types.d.ts

Prevents null values being passed into the backend for these lists after nulls broke ETL.
Also removes InlineChoices / classes related from the code. These were not being used as inline questions (now) reuse the choice type as defined by the inline type; that is, inline numeric questions use Quantity, inline string match questions use StringChoice, etc. There is no case in which this type is not defined, so there was no case these InlineChoices were being used.

Always define inline `choices` and `inlineQuestions` fields

---

src/components/MarkupToolbar.tsx
src/components/popups/PopupInlineQuestionInsert.tsx
src/components/semantic/presenters/InlinePartsPresenter.tsx
src/components/semantic/presenters/questionPresenters.tsx

- Adds an editable field for inline regions' ID
- Prevent "Add drop zone" button appearing outside cloze qs
- Add "Add inline question part" button for content inside inline qs

Inline question QoL improvements

---

src/isaac/markup/latexRendering.ts

A change was made to the `latexRendering.ts` file on isaac-react-app a while ago to allow for different macros on Ada and Isaac. This brings those changes to the content editor.
Looking at the use of all affected macros, this should only change the rendering of "\neq" in the editor from `¬= `to `≠` (which we want), and this old [Logic Test](https://editor.isaacphysics.org/edit/master/content/beta_pages/logic_test.json) beta page (which I'm sure is fine).

Unify MathJax macros with React-App

---

src/components/semantic/registry.tsx

Show a deprecated flag in the editor for tests. This supports a frontend change that hides deprecated tests from users.

Add deprecated flag to tests

---

src/components/semantic/presenters/questionPresenters.tsx
src/isaac-data-types.d.ts

Adds an option to enable the `allowPermutations` flag for Chemistry Questions.
---
Companion PR to [Allow valid permutations of molecules](https://github.com/isaacphysics/chemistry-checker-js/pull/1) for the Chemistry Checker.
(This relies on the new Chemistry Checker, so that should probably be approved and merged in before this is).

Add option to allow Chemistry molecule permutation

---

src/components/semantic/Inserter.tsx
src/components/semantic/registry.tsx

Adds `codeTabs` as a content type. This functions like `Tabs`, but when there is a `codeSnippet` child a user's preferred default programming language is switched to on page load.
This is mostly just a fancy wrapper for Tabs right now, but there is scope to expand this e.g. Automatically selecting codeSnippet type in the editor dropdown.

Add the codeTabs content item to editor

---

src/services/github.ts

We want to enforce all content editor commits to have associated commit messages to be easier to review/debug/check for content pushes/etc. 
This achieves that by hiding the `"*? Edited filename.json"` text from the name window (it will still appear in the commit message itself), and failing/asking the user to retry on an empty commit message. Just failing with no message would've been slightly simpler, but seems unclear and I don't want progress to be lost because of it.
(While making this change, it got me thinking that it could eventually be worth considering adding an entirely new modal for functions like giving warnings about empty/long commit messages, allowing use of a description, greying out the enter button when invalid, disabling invalid characters, etc., but it's a relative …

Hide "Edited filename.json" on save

---

src/components/semantic/presenters/ChoicePresenter.tsx
src/components/semantic/presenters/questionPresenters.tsx
src/components/semantic/props/EditableDocProp.tsx
src/isaac-data-types.d.ts

Add support to the content editor for coordinate questions with any number of dimensions.
This adds a 'dimensions' property to coordinate questions and replaces the current inputs for x and y with some number of inputs as determined by the dimensions set for the question (currently unlimited). Values for each choice (and placeholder values for each question) are stored as a list instead of separate x and y properties.

Add n-dimensional coord Qs

---

src/components/semantic/metaItems.tsx
src/components/semantic/registry.tsx
src/isaac-data-types.d.ts
src/services/emptyDocuments.ts

The two tickboxes are likely still the best way to interact with the underlying list, though; so there are still references to "visibleToStudents".

Remove visibleToStudents quiz property

---

src/components/semantic/metaItems.tsx
src/components/semantic/registry.tsx

Adds a `teacherNotes` field as a textarea in most page types' metadata. Depending on how content use this, we may switch from a textarea to a markdown-compatible component, and potentially move this out of the metadata; this is only intended as a rough, working implementation to get a feel for how it would be used.
Note that this **should not be pushed without content understanding that adding teacherNotes to content will break it on the live (non-redesign) site**.

Add support for teacher notes in fragment & page metadata

---

src/components/semantic/presenters/ChoicePresenter.tsx
src/components/semantic/presenters/InlineQuestionTypePresenter.tsx
src/components/semantic/presenters/questionPresenters.tsx

Note that the `multiLineRegex` prop is forcibly disabled when inline.

Add support for inline regex questions

---

src/components/semantic/presenters/LLMQuestionPresenter.tsx

Related to https://github.com/isaacphysics/isaac-api/pull/691. It should now be _safe_ to include no maxMarks field, but will mean that students always receive a mark total of 0 so it should still be avoided - hence this warning.

Add warning for missing maxMarks field

---

src/components/semantic/presenters/ArrayPropPresenter.tsx
src/components/semantic/presenters/RelatedContentPresenter.tsx

Use a separate function for mapping an existing array prop to an ID to that for mapping content served from the outer context to an ID.

Show content IDs in related content

---

package.json
src/components/TopMenu.tsx
src/components/popups/PopupMenu.tsx
src/services/isaacApi.ts
src/styles/editor.module.css

This also makes a bunch of links actually be links. It has been annoying me for years that we use buttons to open a link in a new tab (I keep trying to middle-click and failing!). Making the links _look_ like the old buttons was more challenging; this isn't nice CSS, but it does work.

Use new site for staging previews

---

src/components/semantic/presenters/LLMQuestionPresenter.tsx
src/components/semantic/props/EditableText.tsx
src/components/semantic/props/NumberDocPropFor.tsx

Also adds support for multiple errors to be displayed at once. This may be helpful if we want to add more errors here, or some to the `CodeMirror` editor.
Largely taken from `IsaacSymbolicQuestion.tsx` in react-app so it should be consistent with that.

Add bracket-counting error to markingFormula validation
